### ISSUE TITLE
Peer_code_review

### ISSUE THREAD

**Issue by emarkees** [naanmohammed/my-portfolio#9]
Great Job done!! 👍,

But there are few thing i thing you could work on so as to make your work looks professional,

for you tag section **[line 71 - 75]**, I think you can use a **[ list {li} ]** sematic tag .

Happy coding 🥂

**Comment by LarryIVC** [comment]
Good job, ⭐  but you can improve it.
When you use the `Page-1_Container` container, you could consider using a `grid `so you can separate the different `sections `using the `gag `property
![image](https://user-images.githubusercontent.com/110146573/221884664-2cbd25f7-47b2-4c41-bda8-5f4d918a2f2f.png)

**Comment by LarryIVC** [comment]
Why don't you consider using the `gag `property in the `works `container? 
This will facilitate you to better control the separation of elements in a uniform way.
![image](https://user-images.githubusercontent.com/110146573/221885134-64a7492e-1d33-4155-ac58-b8945d45bfa8.png)
Happy Coding 🥳

**Comment by naanmohammed** [comment]
Thank you for your suggestions guys, most of your comments have been incorporated into my desktop version.
Happy coding 😁
